/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stopwatch;

/**
 *
 * @author Ghulam Rasool
 */
public class Stopwatch extends javax.swing.JFrame {

    /**
     * Creates new form Stopwatch
     */
    static int milisecond=0;
    static int second=0;
    static int hour=0;
    static int minute=0;
    static boolean state=true;
    public Stopwatch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ms = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ms.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        ms.setText(": 00");
        jPanel1.add(ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 130, 70));

        h.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        h.setText("00");
        jPanel1.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 70));

        m.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        m.setText(": 00");
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 70));

        s.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        s.setText(": 00");
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 110, 70));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        state =true;
        Thread t=new Thread()
        {
            public void run()
            {
                while(true)
                {
                   if(state==true)
                   {
                      try{
                          sleep(1);
                          if(milisecond>1000)
                          {
                              milisecond=0;
                              second++;
                          }
                          if(second>60)
                          {
                              second=0;
                              milisecond=0;
                              minute++;
                          }
                          if(minute>60)
                          {
                              second=0;
                              milisecond=0;
                              hour++;
                              minute++;
                          }
                          ms.setText(" : "+milisecond);
                         milisecond++;
                         m.setText(" : "+minute);
                         h.setText("  "+hour);
                         s.setText(" : "+second);
                      } 
                      catch(Exception e){
                          
                      }
                   }
                   else
                       break;
                }
            }
        };
        t.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        state =false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        state = false;
        milisecond=0;
        second=0;
        minute=0;
        hour=0;
        m.setText("00");
        h.setText("00");
        s.setText("00");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stopwatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel m;
    private javax.swing.JLabel ms;
    private javax.swing.JLabel s;
    // End of variables declaration//GEN-END:variables
}
