/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stopwatch;

import static java.lang.Thread.sleep;
import static stopwatch.Stopwatch.hour;
import static stopwatch.Stopwatch.milisecond;
import static stopwatch.Stopwatch.minute;
import static stopwatch.Stopwatch.second;
import static stopwatch.Stopwatch.state;

/**
 *
 * @author Ghulam Rasool
 */
public class Timer extends javax.swing.JFrame {

    /**
     * Creates new form Timer
     */
    static int milisecond=0;
    static int second=0;
    static int hour=0;
    static int minute=0;
    static boolean state=true;
    static long sand=0;
    public Timer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ms = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        msspin = new javax.swing.JSpinner();
        hspin = new javax.swing.JSpinner();
        mspin = new javax.swing.JSpinner();
        sspin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ms.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        ms.setText(": 00");
        jPanel1.add(ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 140, 70));

        h.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        h.setText("00");
        jPanel1.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 70));

        m.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        m.setText(": 00");
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 70));

        s.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        s.setText(": 00");
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 110, 70));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 90, 40));

        msspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                msspinStateChanged(evt);
            }
        });
        jPanel1.add(msspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, -1));

        hspin.setVerifyInputWhenFocusTarget(false);
        hspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hspinStateChanged(evt);
            }
        });
        jPanel1.add(hspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        mspin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mspinStateChanged(evt);
            }
        });
        jPanel1.add(mspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, -1));

        sspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sspinStateChanged(evt);
            }
        });
        jPanel1.add(sspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hour=0;
        sand=0;
        minute=0;
        milisecond=0;
        h.setText("00");
        m.setText("00");
        s.setText("00");
        ms.setText("00");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        milisecond=Integer.parseInt(""+msspin.getValue());
         second=Integer.parseInt(""+sspin.getValue());
         minute=Integer.parseInt(""+mspin.getValue());
        hour=Integer.parseInt(""+hspin.getValue());
         sand=(hour*60*60*1000)+(minute*60*1000)+(second*1000);
        state =true;
        Thread t=new Thread()
        {
            public void run()
            {
                while(sand>=0)
                {
                   if(state==true)
                   {
                      try{
                          sleep(1);                    
                          sand-=2; 
                          ms.setText(" : "+sand%1000);                         
                          m.setText(" : "+(sand/(60*1000))%60);
                          h.setText("  "+(sand/(60*60*1000))%60);
                          s.setText(" : "+(sand/1000)%60);                         
                      } 
                      catch(Exception e){                          
                      }
                   }
                   else
                       break;
                }
                if(sand<=0);
                    //
            }
        };
        t.start();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        state=false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void msspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_msspinStateChanged
        ms.setText(": "+msspin.getValue());
        
    }//GEN-LAST:event_msspinStateChanged

    private void sspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sspinStateChanged
        s.setText(": "+sspin.getValue());
    }//GEN-LAST:event_sspinStateChanged

    private void mspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mspinStateChanged
        m.setText(": "+mspin.getValue());
    }//GEN-LAST:event_mspinStateChanged

    private void hspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hspinStateChanged
        h.setText(""+hspin.getValue());
    }//GEN-LAST:event_hspinStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel h;
    private javax.swing.JSpinner hspin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel m;
    private javax.swing.JLabel ms;
    private javax.swing.JSpinner mspin;
    private javax.swing.JSpinner msspin;
    private javax.swing.JLabel s;
    private javax.swing.JSpinner sspin;
    // End of variables declaration//GEN-END:variables
}
